/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type WorkflowStatus = "draft" | "in-review" | "approved" | "published" | "archived";

export type VideoEmbed = {
  _type: "videoEmbed";
  url?: string;
  caption?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  canonicalUrl?: string;
  socialImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  jsonLd?: Code;
};

export type ProjectsPage = {
  _id: string;
  _type: "projectsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  description?: string;
  heroEyebrow?: string;
  heroTitle?: string;
  heroLede?: string;
  filterEmptyTitle?: string;
  filterEmptyBody?: string;
  pageEmptyTitle?: string;
  pageEmptyBody?: string;
  contactEmail?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  role?: string;
  summary?: string;
  status?: "Live" | "Maintained" | "Exploration";
  href?: string;
  cta?: string;
  releaseDate?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<string>;
  stack?: Array<string>;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  hook?: string;
  author?: AuthorReference;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  tags?: Array<string>;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  seo?: Seo;
  publishedAt?: string;
  featured?: boolean;
  status?: WorkflowStatus;
  lastReviewedAt?: string;
  approvedAt?: string;
  keyTakeaways?: Array<string>;
  coverVariant?: "default" | "cinematic" | "minimal";
  series?: string;
  scheduledPublishAt?: string;
  crossposting?: {
    devto?: {
      enabled?: boolean;
      articleId?: number;
      url?: string;
      lastSyncedAt?: string;
    };
    hashnode?: {
      enabled?: boolean;
      publicationId?: string;
      postId?: string;
      url?: string;
      lastSyncedAt?: string;
    };
    linkedin?: {
      enabled?: boolean;
      postId?: string;
      url?: string;
      lastSyncedAt?: string;
    };
  };
  analytics?: {
    views?: number;
    uniqueVisitors?: number;
    averageReadTime?: number;
    shares?: {
      twitter?: number;
      linkedin?: number;
      facebook?: number;
    };
    lastUpdatedAt?: string;
  };
  markdownContent?: Markdown;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | {
    _key: string;
  } & Code>;
};

export type Markdown = string;

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type NowPage = {
  _id: string;
  _type: "nowPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoDescription?: string;
  heroEyebrow?: string;
  heroTitle?: string;
  heroLede?: string;
  lastUpdated?: string;
  nowItems?: Array<string>;
  nextItems?: Array<string>;
  laterItems?: Array<string>;
  signalsHeading?: string;
  signalsLede?: string;
  executionSignals?: Array<{
    title?: string;
    body?: string;
    _key: string;
  }>;
  githubHeading?: string;
  githubLede?: string;
};

export type Divider = {
  _type: "divider";
  style?: "line" | "dots" | "asterisks" | "space";
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Callout = {
  _type: "callout";
  variant?: "info" | "warning" | "success" | "error";
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  _type: "image";
  _key: string;
} | {
  _key: string;
} & Code | {
  _key: string;
} & Callout | {
  _key: string;
} & VideoEmbed | {
  _key: string;
} & Divider>;

export type BlogPage = {
  _id: string;
  _type: "blogPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageDescription?: string;
  heroEyebrow?: string;
  heroTitle?: string;
  heroLede?: string;
  emptyStateTitle?: string;
  emptyStateBody?: string;
  editorialDirectionHeading?: string;
  editorialDirectionLede?: string;
  pillars?: Array<{
    icon?: string;
    title?: string;
    body?: string;
    _key: string;
  }>;
  archiveHeading?: string;
  archiveLede?: string;
  allArticlesLabel?: string;
  loadOlderLabel?: string;
  filterEmptyState?: string;
  spotlightTags?: Array<string>;
  placeholderCards?: Array<{
    title?: string;
    summary?: string;
    href?: string;
    tags?: Array<string>;
    _key: string;
  }>;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  socialLinks?: {
    github?: string;
    linkedin?: string;
    twitter?: string;
    website?: string;
  };
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoDescription?: string;
  heroEyebrow?: string;
  heroTitle?: string;
  heroLede?: string;
  manifestoLabel?: string;
  manifestoTitle?: string;
  manifestoCopy?: string;
  proofBullets?: Array<string>;
  principles?: Array<{
    title?: string;
    body?: string;
    _key: string;
  }>;
  timelineHeading?: string;
  timelineLede?: string;
  timelineItems?: Array<{
    year?: string;
    title?: string;
    body?: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = WorkflowStatus | VideoEmbed | SanityImageAssetReference | Seo | ProjectsPage | Project | SanityImageCrop | SanityImageHotspot | Slug | AuthorReference | CategoryReference | Post | Markdown | Code | NowPage | Divider | Category | Callout | BlockContent | BlogPage | Author | AboutPage | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

