/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type WorkflowStatus = "draft" | "in-review" | "approved" | "published" | "archived";

export type VideoEmbed = {
  _type: "videoEmbed";
  url?: string;
  caption?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type TopicReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topic";
};

export type Topic = {
  _id: string;
  _type: "topic";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  audience?: string;
  positioning?: string;
  seoFraming?: string;
  description?: string;
  archiveIntro?: string;
  canonicalTags?: Array<string>;
  accentImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  featuredPostRules?: string;
  relatedTopics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type ContentBriefReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contentBrief";
};

export type SourceReference = {
  _id: string;
  _type: "sourceReference";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  url?: string;
  sourceType?:
    | "article"
    | "documentation"
    | "video"
    | "paper"
    | "talk"
    | "repository"
    | "interview"
    | "dataset";
  author?: string;
  reliability?: "high" | "medium" | "low";
  confidenceNotes?: string;
  capturedExcerpt?: string;
  notes?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  relatedPosts?: Array<
    {
      _key: string;
    } & PostReference
  >;
  relatedBriefs?: Array<
    {
      _key: string;
    } & ContentBriefReference
  >;
};

export type Series = {
  _id: string;
  _type: "series";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  positioning?: string;
  description?: string;
  order?: number;
  canonicalCta?: string;
  relatedPosts?: Array<
    {
      _key: string;
    } & PostReference
  >;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  canonicalUrl?: string;
  socialImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
  jsonLd?: Code;
};

export type FeaturedGithubRepo = {
  _id: string;
  _type: "featuredGithubRepo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  repoFullName?: string;
  displayTitle?: string;
  description?: string;
  category?: string;
  featured?: boolean;
  order?: number;
  showRepositoryLink?: boolean;
  showPrivate?: boolean;
  visibleInProofOfWork?: boolean;
};

export type Divider = {
  _type: "divider";
  style?: "line" | "dots" | "asterisks" | "space";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type BlogPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogPage";
};

export type AboutPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aboutPage";
};

export type NowPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "nowPage";
};

export type ProjectsPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "projectsPage";
};

export type ContentBrief = {
  _id: string;
  _type: "contentBrief";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  status?: "idea" | "briefed" | "drafting" | "in-review" | "ready" | "published" | "archived";
  audience?: string;
  intent?: string;
  thesis?: string;
  targetKeyword?: string;
  distributionGoals?: Array<string>;
  dueDate?: string;
  notes?: string;
  linkedPost?: PostReference;
  linkedProject?: ProjectReference;
  linkedPage?: BlogPageReference | AboutPageReference | NowPageReference | ProjectsPageReference;
};

export type ProjectsPage = {
  _id: string;
  _type: "projectsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  description?: string;
  heroEyebrow?: string;
  heroTitle?: string;
  heroLede?: string;
  filterEmptyTitle?: string;
  filterEmptyBody?: string;
  pageEmptyTitle?: string;
  pageEmptyBody?: string;
  contactEmail?: string;
  seo?: Seo;
  pageIntent?: string;
  changeNotes?: string;
};

export type NowPage = {
  _id: string;
  _type: "nowPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoDescription?: string;
  heroEyebrow?: string;
  heroTitle?: string;
  heroLede?: string;
  lastUpdated?: string;
  nowItems?: Array<string>;
  nextItems?: Array<string>;
  laterItems?: Array<string>;
  signalsHeading?: string;
  signalsLede?: string;
  executionSignals?: Array<{
    title?: string;
    body?: string;
    _key: string;
  }>;
  githubHeading?: string;
  githubLede?: string;
  seo?: Seo;
  pageIntent?: string;
  changeNotes?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  role?: string;
  summary?: string;
  status?: "Live" | "Maintained" | "Exploration";
  href?: string;
  cta?: string;
  releaseDate?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<string>;
  stack?: Array<string>;
  order?: number;
};

export type SeriesReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "series";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SourceReferenceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sourceReference";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  brief?: ContentBriefReference;
  audience?: string;
  intent?: string;
  targetKeyword?: string;
  topics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  relatedSeries?: Array<
    {
      _key: string;
    } & SeriesReference
  >;
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  tags?: Array<string>;
  featured?: boolean;
  summary?: string;
  hook?: string;
  keyTakeaways?: Array<string>;
  sourceReferences?: Array<
    {
      _key: string;
    } & SourceReferenceReference
  >;
  pullQuotes?: Array<{
    quote?: string;
    attribution?: string;
    sourceUrl?: string;
    _key: string;
  }>;
  furtherReading?: Array<{
    title?: string;
    href?: string;
    note?: string;
    _key: string;
  }>;
  markdownContent?: Markdown;
  content?: BlockContent;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroCreativeNotes?: string;
  coverVariant?: "default" | "cinematic" | "minimal";
  seo?: Seo;
  cta?: {
    label?: string;
    href?: string;
    intent?: string;
  };
  distributionPackage?: {
    newsletterBlurb?: string;
    shortSocialPost?: string;
    longSocialPost?: string;
    teaserQuote?: string;
    ctaLabel?: string;
    generatedAt?: string;
  };
  crossposting?: {
    devto?: {
      enabled?: boolean;
      articleId?: number;
      url?: string;
      status?: string;
      lastResultMessage?: string;
      lastSyncedAt?: string;
    };
    hashnode?: {
      enabled?: boolean;
      publicationId?: string;
      postId?: string;
      url?: string;
      status?: string;
      lastResultMessage?: string;
      lastSyncedAt?: string;
    };
    linkedin?: {
      enabled?: boolean;
      postId?: string;
      url?: string;
      status?: string;
      lastResultMessage?: string;
      lastSyncedAt?: string;
    };
    manualTriggerAt?: string;
  };
  refreshCadence?: "monthly" | "quarterly" | "biannual" | "annual" | "evergreen";
  evergreenStatus?: "current" | "needs-refresh" | "refreshing" | "timeless";
  publishedAt?: string;
  status?: WorkflowStatus;
  lastReviewedAt?: string;
  approvedAt?: string;
  tagRefreshRequestedAt?: string;
  distributionRequestedAt?: string;
  refreshRequestedAt?: string;
  scheduledPublishAt?: string;
  analytics?: {
    views?: number;
    uniqueVisitors?: number;
    averageReadTime?: number;
    shares?: {
      twitter?: number;
      linkedin?: number;
      facebook?: number;
    };
    lastUpdatedAt?: string;
  };
  refreshReview?: {
    status?: "monitor" | "refresh-soon" | "rewrite" | "archive";
    summary?: string;
    recommendedChanges?: Array<string>;
    generatedAt?: string;
  };
  series?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & Code)
  | ({
      _key: string;
    } & Callout)
  | ({
      _key: string;
    } & VideoEmbed)
  | ({
      _key: string;
    } & Divider)
>;

export type Markdown = string;

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  positioning?: string;
  canonicalTags?: Array<string>;
  archiveIntro?: string;
};

export type Callout = {
  _type: "callout";
  variant?: "info" | "tip" | "warning" | "success" | "error";
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type BlogPage = {
  _id: string;
  _type: "blogPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageDescription?: string;
  heroEyebrow?: string;
  heroTitle?: string;
  heroLede?: string;
  emptyStateTitle?: string;
  emptyStateBody?: string;
  editorialDirectionHeading?: string;
  editorialDirectionLede?: string;
  pillars?: Array<{
    icon?: string;
    title?: string;
    body?: string;
    _key: string;
  }>;
  archiveHeading?: string;
  archiveLede?: string;
  allArticlesLabel?: string;
  loadOlderLabel?: string;
  filterEmptyState?: string;
  spotlightTags?: Array<string>;
  placeholderCards?: Array<{
    title?: string;
    summary?: string;
    href?: string;
    tags?: Array<string>;
    _key: string;
  }>;
  seo?: Seo;
  pageIntent?: string;
  changeNotes?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  role?: string;
  expertise?: Array<string>;
  voice?: string;
  featuredTopics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  socialLinks?: {
    github?: string;
    linkedin?: string;
    twitter?: string;
    website?: string;
  };
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoDescription?: string;
  heroEyebrow?: string;
  heroTitle?: string;
  heroLede?: string;
  manifestoLabel?: string;
  manifestoTitle?: string;
  manifestoCopy?: string;
  proofBullets?: Array<string>;
  principles?: Array<{
    title?: string;
    body?: string;
    _key: string;
  }>;
  timelineHeading?: string;
  timelineLede?: string;
  timelineItems?: Array<{
    year?: string;
    title?: string;
    body?: string;
    _key: string;
  }>;
  seo?: Seo;
  pageIntent?: string;
  changeNotes?: string;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityVideoMetadataPlayback = {
  _type: "sanity.videoMetadata.playback";
  policy?: string;
};

export type SanityVideoMetadata = {
  _type: "sanity.videoMetadata";
  duration?: number;
  framerate?: number;
  aspectRatio?: number;
  hasAudio?: boolean;
  codec?: string;
  bitrate?: number;
};

export type SanityVideoAsset = {
  _id: string;
  _type: "sanity.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  creditLine?: string;
  metadata?: SanityVideoMetadata;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
};

export type SanityVideo = {
  _type: "sanity.video";
  asset?: unknown;
  media?: unknown;
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<
    {
      _key: string;
    } & SanityAssistInstructionTask
  >;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<
    {
      _key: string;
    } & SanityAssistSchemaTypeField
  >;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type AssistInstructionContextReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "assist.instruction.context";
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference?: AssistInstructionContextReference;
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message?: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }
    | ({
        _key: string;
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string;
      } & SanityAssistInstructionContext)
    | ({
        _key: string;
      } & SanityAssistInstructionUserInput)
  >;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<
    | ({
        _key: string;
      } & SanityAssistOutputField)
    | ({
        _key: string;
      } & SanityAssistOutputType)
  >;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<
    {
      _key: string;
    } & SanityAssistInstruction
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | WorkflowStatus
  | VideoEmbed
  | SanityImageAssetReference
  | TopicReference
  | Topic
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | PostReference
  | ContentBriefReference
  | SourceReference
  | Series
  | Seo
  | FeaturedGithubRepo
  | Divider
  | ProjectReference
  | BlogPageReference
  | AboutPageReference
  | NowPageReference
  | ProjectsPageReference
  | ContentBrief
  | ProjectsPage
  | NowPage
  | Project
  | SeriesReference
  | AuthorReference
  | CategoryReference
  | SourceReferenceReference
  | Post
  | BlockContent
  | Markdown
  | Category
  | Callout
  | BlogPage
  | Author
  | AboutPage
  | Code
  | SanityVideoMetadataPlayback
  | SanityVideoMetadata
  | SanityVideoAsset
  | SanityVideo
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
