name = "tulio-personal-website"
compatibility_date = "2025-10-10"

[assets]
directory = "./dist"

[vars]
PUBLIC_SANITY_PROJECT_ID = "61249gtj"
PUBLIC_SANITY_DATASET = "production"
SANITY_API_READ_TOKEN = "skonmkNRCv4QcFFbUz8qpZevmOZ1nyKtLvaEVWjCus0DE7t4uWMTDvVFvCAvJYDXwJS33XZmEquiJgpFgUeomPSTwtFgPGjIPfJM1GVK5ts31YH4JtqEhacMVxTHscpauyQpPWF2bWo5GMMsc6Ny054N1L1DltLysHdkblGTAUOQuYUwWZ4n"
