import { DocumentTextIcon } from "@sanity/icons";
import { defineArrayMember, defineField, defineType } from "sanity";

export default defineType({
  name: "blogPage",
  title: "Blog Page",
  type: "document",
  icon: DocumentTextIcon,
  fieldsets: [
    { name: "hero", title: "Hero", options: { collapsible: true, collapsed: false } },
    {
      name: "editorial",
      title: "Editorial Direction",
      options: { collapsible: true, collapsed: false },
    },
    { name: "archive", title: "Archive Settings", options: { collapsible: true, collapsed: true } },
    { name: "empty", title: "Empty States", options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    defineField({
      name: "pageDescription",
      title: "Page Description",
      type: "text",
      fieldset: "hero",
      rows: 3,
      validation: (rule) => rule.required().min(40).max(220),
    }),
    defineField({
      name: "heroEyebrow",
      title: "Hero Eyebrow",
      type: "string",
      fieldset: "hero",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroTitle",
      title: "Hero Title",
      type: "string",
      fieldset: "hero",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroLede",
      title: "Hero Lede",
      type: "text",
      fieldset: "hero",
      rows: 3,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "emptyStateTitle",
      title: "Empty State Title",
      type: "string",
      fieldset: "empty",
      initialValue: "No posts yet",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "emptyStateBody",
      title: "Empty State Body",
      type: "text",
      fieldset: "empty",
      rows: 3,
      initialValue:
        "The essays are still in draft. RSS and Atom will pick up the first post as soon as it lands.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "editorialDirectionHeading",
      title: "Editorial Direction Heading",
      type: "string",
      fieldset: "editorial",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "editorialDirectionLede",
      title: "Editorial Direction Lede",
      type: "text",
      fieldset: "editorial",
      rows: 2,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "pillars",
      title: "Editorial Pillars",
      type: "array",
      fieldset: "editorial",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({
              name: "icon",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "title",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "body",
              type: "text",
              rows: 3,
              validation: (rule) => rule.required(),
            }),
          ],
          preview: { select: { title: "title", subtitle: "body" } },
        }),
      ],
      validation: (rule) => rule.required().min(2).max(6),
    }),
    defineField({
      name: "archiveHeading",
      title: "Archive Heading",
      type: "string",
      fieldset: "archive",
      initialValue: "By year",
    }),
    defineField({
      name: "archiveLede",
      title: "Archive Lede",
      type: "text",
      fieldset: "archive",
      rows: 2,
      initialValue: "A simple view of what was published and when.",
    }),
    defineField({
      name: "allArticlesLabel",
      title: "All Articles Filter Label",
      type: "string",
      fieldset: "archive",
      initialValue: "All posts",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "loadOlderLabel",
      title: "Load Older Label",
      type: "string",
      fieldset: "archive",
      initialValue: "Load older posts",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "filterEmptyState",
      title: "Filtered Empty State",
      type: "string",
      fieldset: "empty",
      initialValue: "No posts match this filter yet.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "spotlightTags",
      title: "Spotlight Tags",
      type: "array",
      fieldset: "archive",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.min(1).max(10),
    }),
    defineField({
      name: "placeholderCards",
      title: "Placeholder Cards",
      type: "array",
      fieldset: "empty",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({
              name: "title",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "summary",
              type: "text",
              rows: 3,
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "href",
              type: "string",
              initialValue: "/blog/",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "tags",
              type: "array",
              of: [defineArrayMember({ type: "string" })],
              validation: (rule) => rule.max(4),
            }),
          ],
          preview: { select: { title: "title", subtitle: "summary" } },
        }),
      ],
      validation: (rule) => rule.max(6),
    }),
  ],
  preview: {
    select: { title: "heroTitle", subtitle: "pageDescription" },
  },
});
