import { CalendarIcon } from "@sanity/icons";
import { defineArrayMember, defineField, defineType } from "sanity";

export default defineType({
  name: "nowPage",
  title: "Now Page",
  type: "document",
  icon: CalendarIcon,
  fieldsets: [
    { name: "hero", title: "Hero", options: { collapsible: true, collapsed: false } },
    {
      name: "nowNextLater",
      title: "Now / Next / Later",
      options: { collapsible: true, collapsed: false },
    },
    { name: "signals", title: "Signals", options: { collapsible: true, collapsed: false } },
    { name: "github", title: "GitHub", options: { collapsible: true, collapsed: true } },
    { name: "ops", title: "Editorial Ops", options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    defineField({
      name: "seoDescription",
      title: "SEO Description",
      type: "text",
      fieldset: "hero",
      rows: 3,
      validation: (rule) => rule.required().min(30).max(220),
    }),
    defineField({
      name: "heroEyebrow",
      title: "Hero Eyebrow",
      type: "string",
      fieldset: "hero",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroTitle",
      title: "Hero Title",
      type: "string",
      fieldset: "hero",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroLede",
      title: "Hero Lede",
      type: "text",
      fieldset: "hero",
      rows: 3,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "lastUpdated",
      title: "Last Updated",
      type: "date",
      fieldset: "hero",
      options: { dateFormat: "MMMM D, YYYY" },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "nowItems",
      title: "Now Items",
      type: "array",
      fieldset: "nowNextLater",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.required().min(1).max(8),
    }),
    defineField({
      name: "nextItems",
      title: "Next Items",
      type: "array",
      fieldset: "nowNextLater",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.required().min(1).max(8),
    }),
    defineField({
      name: "laterItems",
      title: "Later Items",
      type: "array",
      fieldset: "nowNextLater",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.required().min(1).max(8),
    }),
    defineField({
      name: "signalsHeading",
      title: "Signals Heading",
      type: "string",
      fieldset: "signals",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "signalsLede",
      title: "Signals Lede",
      type: "text",
      fieldset: "signals",
      rows: 2,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "executionSignals",
      title: "Execution Signals",
      type: "array",
      fieldset: "signals",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({
              name: "title",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "body",
              type: "text",
              rows: 2,
              validation: (rule) => rule.required(),
            }),
          ],
          preview: { select: { title: "title", subtitle: "body" } },
        }),
      ],
      validation: (rule) => rule.required().min(2).max(8),
    }),
    defineField({
      name: "githubHeading",
      title: "GitHub Heading",
      type: "string",
      fieldset: "github",
      initialValue: "GitHub activity",
    }),
    defineField({
      name: "githubLede",
      title: "GitHub Lede",
      type: "text",
      fieldset: "github",
      rows: 2,
      initialValue: "Recent commits across active repositories.",
    }),
    defineField({
      name: "seo",
      title: "SEO Metadata",
      type: "seo",
      fieldset: "ops",
      options: {
        collapsible: true,
        collapsed: true,
      },
    }),
    defineField({
      name: "pageIntent",
      title: "Page Intent",
      type: "text",
      rows: 3,
      fieldset: "ops",
      validation: (rule) => rule.max(240),
    }),
    defineField({
      name: "changeNotes",
      title: "Change Notes",
      type: "text",
      rows: 4,
      fieldset: "ops",
      validation: (rule) => rule.max(480),
    }),
  ],
  preview: {
    select: { title: "heroTitle", subtitle: "lastUpdated" },
  },
});
